### ISSUE TITLE
[BUG] types field is not set in the package.json

### ISSUE THREAD

**Issue by xeoneux** [image-component/react-image-shadow#11]
### 🐛 Bug 描述 Bug description

Cannot load typings for the project while using it.

### 🏞 期望结果 Desired result

Bundling types with the library would help using it in a typescript based project.

### 🚑 其他信息 Other information

Nothing else! Really love the shadow effect it creates under the images :smile:

**Comment by xrkffgg** [comment]
```diff
+ react-image-shadow@1.1.2
```

**Comment by xeoneux** [comment]
Thanks! :)
